[server]
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
base = "dark"

[client]
toolbarMode = "minimal"
showErrorDetails = false
showToolbar = false

[global]
developmentMode = false
sharingMode = "off"
